BranchSDK/src/BranchIO/Defines.cpp, BranchSDK/src/BranchIO/Defines.h, BranchSDK/src/BranchIO/Event/Event.cpp, BranchSDK/src/BranchIO/Event/Event.h, BranchSDK/test/EventTest.cpp
SDK-240 -- Add support for customer_event_alias
`customer_event_alias` is a new key/value pair for V2 standard events.
This ticket adds `setCustomerEventAlias()` to the Event class.
* Sample app should compile and run
* New unit test was written to demonstrate usage.
Note that we aren't able to (easily) pull out components of JSON.   For purposes of testing this feature I added a print statement and verified that the new field is in there.
```
{
"branch_key": "key_live_xxx",
"custom_data": {
"Custom": "My Custom Data Property"
},
"event_data": {
"ad_type": "NATIVE",
"affiliation": "My Affiliation",
"coupon": "My Coupon",
"currency": "My CurrencyType",
"customer_event_alias": "My Alias",
"description": "My Description",
"revenue": 99.99,
"search_query": "My SearchQuery",
"shipping": 9.99, …
```
=> SDK-240 -- Add support for customer_event_alias

BranchSDK-Samples/console/example/example.cpp
SDK-468 -- Fix sample crashing issue
The C++ SDK "example" app was crashing if you attempted to access the link but it wasn't provided.  Specifically, if you select option #1 from the menu.
Note that I did some general cleanup around this as well.
* Sample app should compile and run
This is a sample.
=> SDK-468 -- Fix sample crashing issue

BranchSDK/src/BranchIO/AdvertiserInfo.cpp, BranchSDK/src/BranchIO/AdvertiserInfo.h, BranchSDK/src/BranchIO/Defines.cpp, BranchSDK/src/BranchIO/Defines.h, BranchSDK/src/BranchIO/Event/Event.cpp, BranchSDK/src/BranchIO/Event/Event.h, BranchSDK/src/BranchIO/Event/StandardEvent.cpp, BranchSDK/src/BranchIO/Event/StandardEvent.h, BranchSDK/src/BranchIO/Request.cpp
SDK-601 -- AdvertiserInfo has toXString instead of toString
One of the earlier commits introduced a method toXString().
Note that I did some general cleanup around "toString" and "stringify".   In general the semantics going forward should be that "toString()" takes a class and turns it into a string, while "stringify()" takes a constant and turns that into a string.
JSONObject is the exception (revisit) as POCO used stringify at its base.
* Sample apps should compile and run
This is mostly changing names
=> SDK-601 -- AdvertiserInfo has toXString instead of toString

BranchSDK/src/BranchIO/Util/Storage.h
WindowsStorage.h didn't get migrated during the last set of refactoring.
This is a quick fix to update the path.
=> Fixed Windows Storage file location

BranchSDK-Samples/Windows/ColorPicker/ColorPicker.cpp
Win64 and Win32 have different defines available.  GWL_HINSTANCE isn't available on Win64 which caused the ColorPicker demo app to break
=> SDK-610 -- Invalid define

BranchSDK-Samples/console/example/example.cpp, BranchSDK/src/BranchIO/Branch.cpp, BranchSDK/src/BranchIO/Branch.h, BranchSDK/src/BranchIO/Defines.cpp, BranchSDK/src/BranchIO/Defines.h, BranchSDK/src/BranchIO/Event/IdentityEvent.h, BranchSDK/src/BranchIO/Event/SessionEvent.h, BranchSDK/src/BranchIO/SessionInfo.cpp, BranchSDK/src/BranchIO/SessionInfo.h
SDK-615 -- Implementation of setIdentity() and logout()
The C++ SDK needs to be able to identify users uniquely. In other SDKs, this is typically done by `setIdentity()`.
The method `logout()` is typically paired with this.
NOTE that I also added enable/disable tracking to the example app.   This functionality was already in the SDK but wasn't exposed via. the sample.
* Sample app should compile and run
While using the Example sample to test it should be noted that `setIdentity()` and `logout()` are -- at this point -- the only APIs that require an active session.   Calling these APIs prior to a session will generate an error callback.
Further, there is a bit of a race condition here -- because the session must *successfully complete* prior to calling setIdentity.
This is core Branch …
=> SDK-615 -- Implementation of setIdentity and logout

CMakeLists.txt, conanfile.py, rmake
SDK-630 -- Better conan version management
We have some things hard coded into our scripts.  Essentially we are always generating version 0.1.0/testing
We'd like to generate new versions like:
* 1.0.0/stable   -- (master branch)
* 1.0.0/staging -- (Staging branch)
* 1.0.0/testing  -- (All other branches)
NOTE that we don't want to go directly to 1.0.0 right now -- we need to go to 0.2.0 until our testing of other features is complete.
On this branch, the `rmake` script should generate version 0.2.0/testing
Once this gets merged to Staging, we can verify that the version becomes 0.2.0/staging
Once this gets merged to master, we can verify that the version becomes 0.2.0/stable
This is a build script change only
=> SDK-630 -- Better conan version management

BranchSDK-Samples/Windows/ColorPicker/conanfile.txt, BranchSDK-Samples/console/storagedemo/storagedemo.cpp, BranchSDK/CMakeLists.txt, BranchSDK/src/BranchIO/AdvertiserInfo.cpp, BranchSDK/src/BranchIO/AdvertiserInfo.h, BranchSDK/src/BranchIO/Branch.cpp, BranchSDK/src/BranchIO/Branch.h, BranchSDK/src/BranchIO/Event/Event.cpp, BranchSDK/src/BranchIO/Event/Event.h, BranchSDK/src/BranchIO/Event/IdentityEvent.h, BranchSDK/src/BranchIO/PropertyManager.cpp, BranchSDK/src/BranchIO/PropertyManager.h, BranchSDK/src/BranchIO/SessionInfo.cpp, BranchSDK/src/BranchIO/SessionInfo.h, BranchSDK/src/BranchIO/Util/IStorage.h, BranchSDK/src/BranchIO/Util/Log.cpp, BranchSDK/src/BranchIO/Util/Log.h, BranchSDK/src/BranchIO/Util/RequestManager.cpp, BranchSDK/src/BranchIO/Util/RequestManager.h, BranchSDK/src/BranchIO/Util/UnixStorage.cpp, BranchSDK/src/BranchIO/Util/UnixStorage.h, BranchSDK/src/BranchIO/Util/WindowsStorage.cpp, BranchSDK/src/BranchIO/Util/WindowsStorage.h, BranchSDK/test/StorageTest.cpp
SDK-632 -- Disable Tracking option does not persist throughout multiple sessions.
We were not saving the Tracking State to shared preferences.   
1. Disable tracking
2. Send an open request and verify it's unsuccessful
3. Close the app
4. Open it again
5. Send another Open Request
Expected Results:  Verify the request was *not* sent, nor should any other requests be sent until Enable Tracking is sent.
Lots and lots of changes happened to make this work.
=> SDK-632 -- Disable Tracking option does not persist throughout multiple sessions.

BranchSDK-Samples/Windows/ColorPicker/ColorPicker.cpp, BranchSDK/src/BranchIO/LinkInfo.cpp, BranchSDK/src/BranchIO/LinkInfo.h, BranchSDK/test/LinkInfoTest.cpp
SDK-647 -- Standardize create link API
While producing documentation, I found that Short and Long Links have a slightly different API.
Quick fix to standardize these.
* Unit Tests Pass
Simple API change.
=> SDK-647 -- Standardize create link API

BranchSDK-Samples/console/example/example.cpp
SDK-648 -- example sample issues with missing properties
QA discovered an issue where – if you don't have the branch_link property in the properties file, the sample will crash, and crash hard.
The issue is that the example.properties file that _I_ have been using has a branch_link.   If the properties doesn't have that -- when it tries to access that (missing) property the Application class fails.
1. make sure the example.properties doesn't have a branch_link defined
2. run option #1 or #7 
Test these steps before and after the change
example sample change only.
=> SDK-648 -- example sample issues with missing properties

BranchSDK/src/BranchIO/Branch.cpp, BranchSDK/src/BranchIO/Branch.h, BranchSDK/src/BranchIO/Event/BaseEvent.cpp, BranchSDK/src/BranchIO/Event/BaseEvent.h, BranchSDK/src/BranchIO/Event/Event.cpp, BranchSDK/src/BranchIO/Event/Event.h, BranchSDK/src/BranchIO/Event/IdentityEvent.h, BranchSDK/src/BranchIO/Event/SessionEvent.h, BranchSDK/src/BranchIO/LinkInfo.cpp, BranchSDK/src/BranchIO/LinkInfo.h, BranchSDK/src/BranchIO/Util/RequestManager.cpp, BranchSDK/src/BranchIO/Util/RequestManager.h
SDK-644 -- Create a base event interface
The C++ SDK development cycle started with Events, and with those events you have the ability to set a number of properties that generally relate to commerce-type events.
Much of the infrastructure that built up allowed anything that was an Event or Event subclass to be placed on the queue, and it knew how to packaged itself up and indicate which endpoint it needed to go to.
The issue here is that there are things that are saying they are Events, while they have no business having commerce type attributes.
This is simply solved by creating a new base (like, "BaseEvent"), and slightly modifying the polymorphism graph correctly.
* Unit Tests Pass
* Samples continue to run correctly
This was a fairly minor refactor, and none of the samples needed to …
=> SDK-644 -- Create a base event interface

BranchSDK-Samples/Windows/ColorPicker/conanfile.txt, conanfile.py
SDK-621 -- Release 1.0.0 (Testing Release Process)
This branch is trying to reconcile how to do Conan package management, such that we can use git as our repo for building.
There is some black magic in here, I won't lie.  
The [instructions](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm) say to do this:
```
scm = {
"type": "git",  # Use "type": "svn", if local repo is managed using SVN
"subfolder": "hello",
"url": "auto",
"revision": "auto"
}
```
Our implementation in `conanfile.py` matches those now.
```
scm = {
"type": "git",
"url": "auto",
"revision": "auto"
}
```
The resultant package (this one is a little behind, as I've done additional pushes)
```
scm = {"revision": "7c1e71b525e2b13b30d4de6e634c393cf148ab25",
"type": "git", …
```
=> SDK-621 -- Release process testing

BranchSDK-Samples/Windows/BranchDemo/conanfile.txt, BranchSDK/src/BranchIO/Util/RequestManager.cpp, BranchSDK/src/BranchIO/Version.h, CMakeLists.txt, conanfile.py, rmake, rmake.bat
INTENG-9716
- Update Poco dependency to 1.9.4. This addresses a consistent SSL failure on Windows.
The Poco requirement is `[~=1.9.4]`, which permits later patch upgrades via `conan install --update`.
- Update SDK version to 1.0.1.
- Removed some options that are no longer used (`git_branch`, `source_folder`).
- Updated some package metadata (specifically the homepage property to point to help.branch.io).
See me for details.
=> [INTENG-9716] Update Poco

BranchSDK-Samples/Windows/BranchDemo/conanfile.txt, BranchSDK-Samples/Windows/ColorPicker/conanfile.txt, BranchSDK-Samples/Windows/TestBed/conanfile.txt, ChangeLog.md, conanfile.py
SDK-973 -- Release v 1.0.1 of C++ SDK to Conan
Releasing version 1.0.1 with Poco update to Conan.
This is in our bintray remote now. Add the remote if you don't have it already:
```bash
$ conan remote add branch https://api.bintray.com/conan/branchsdk/cpp-branch-deep-linking-attribution
```
Use `conan remote list` to see currently configured remotes.
You can call the remote whatever you like other than `branch`. In some commands you may specify it by name via `-r branch`. In others all remotes are automatically searched. It's not obvious that v 1.0.0 was ever released to conan-center.
To see it:
```bash
$ conan search -r branch --raw BranchIO/1.0.1@branch/stable
```
To build with it, use this in your conanfile.txt:
```
[requires]
BranchIO/1.0.1@branch/stable
[options] …
```
=> [SDK-973] Release v 1.0.1

BranchSDK/src/BranchIO/Version.h, CMakeLists.txt, ChangeLog.md, conanfile.py
This is just a manual version bump, since there are some structural issues in the repo that make it hard to automate version update by propagating it with `cmake configure`, and a ChangeLog update.
In a future build, I want to be able to set the version in CMakeLists.txt and then generate conanfile.py and Version.h, but that risks destabilizing things in advance of an important release, so leaving this manual for the moment.
=> [SDK-988] release 1.1.0

BranchSDK/src/BranchIO/Branch.cpp, BranchSDK/src/BranchIO/Version.h
We have very generic macro names that can potentially cause conflicts in a public header.
=> Preprocessor macros do not honor namespacing.

BranchSDK-Samples/Windows/BranchDemo/conanfile.txt, BranchSDK-Samples/Windows/ColorPicker/conanfile.txt, BranchSDK-Samples/Windows/TestBed/conanfile.txt, BranchSDK/src/BranchIO/Version.h, CMakeLists.txt, ChangeLog.md, conanfile.py
Bumped to version 1.1.1.
Updated examples to use `BranchIO/1.1.1@branch/stable`.
This has been tagged and released to Conan as `BranchIO/1.1.1@branch/stable`.
=> Release 1.1.1

BranchSDK-Samples/Windows/TestBed/BranchOperations.cpp, BranchSDK-Samples/Windows/TestBed/BranchOperations.h, BranchSDK-Samples/Windows/TestBed/Button.cpp, BranchSDK-Samples/Windows/TestBed/Button.h, BranchSDK-Samples/Windows/TestBed/TestBed.cpp
Added a button labeled "Disable Tracking" or "Enable Tracking," depending on the current state, to exercise this functionality.
=> [SDK-1059] Disable tracking in testbed

rmake
"bash" on WSL seems to be missing some common bashisms like `[[` and `pushd/popd`. This enables `rmake` in that environment.
=> Some bash fixes for the Windows Subsystem for Linux

BranchSDK/src/BranchIO/Branch.cpp
In order to properly initialize from storage, the Branch key prefix needs to be set before the Branch constructor is executed. Without this change, the disable tracking setting is not really persistent with per-app storage.
This also fixes a memory leak in `Branch::openSession`.
=> Fix setting initialization

BranchSDK/src/BranchIO/DeviceInfo.cpp, BranchSDK/test/BranchDeviceInfoTest.cpp
We should only send semver-style OS versions to the API Open service. The service will also be updated to handle this case, but this should be fixed in the SDK.
=> [SDK-1071] fix os version

BranchSDK-Samples/Windows/TestBed/TextField.cpp, BranchSDK-Samples/Windows/TestBed/TextField.h
In a long-term automated test suite, the size of the output Edit control can grow without bound. This change limits the size to avoid running out of memory.
=> Limit size of text output in TestBed

BranchSDK-Samples/Windows/ColorPicker/ColorPicker.cpp, BranchSDK-Samples/Windows/TestBed/TestBed.cpp
TestBed was attempting something too fancy for the SDK. It would first initialize Branch, posting an open request immediately on launch. Then it would check for a running instance of the app. If it detected an instance of the app already running, it would wait for the open response then forward the response to the running instance. This was done in part to help win any race with the Web SDK, though that has also been addressed by `$desktop_web_open_delay_ms`. Unfortunately, this doesn't work correctly at the moment. The running process has to execute any call to `Branch::openSession`, or its in-memory Session ID won't be updated when the new open is executed. It will just report the open results and continue using the previous Session ID.
This change just passes the URI off to the running …
=> Simplify TestBed open logic

BranchSDK-Samples/Windows/TestBed/README.md
This indicates the correct location of the SDK logs left by TestBed. The README was not updated after the code changed.
=> Update testbed README

BranchSDK/src/BranchIO/Util/APIClientSession.cpp
This adds the value of any `X-Branch-Request-Id` header in an API response to the logs on Debug level, with the status.
```
2020-11-16-15:48:31.629144|Debug|9504|APIClientSession.cpp:144[processResponse]|[cb1f220e9a5148cd8e4f2bb082b7b953-2020111615] 200 OK
2020-11-16-15:48:31.631140|Verbose|9504|APIClientSession.cpp:155[processResponse]|Response body: {"data":"{\"+clicked_branch_link\":false,\"+is_first_session\":true}","device_fingerprint_id":"856910924455859796","identity_id":"856910924484511566","link":"https:\/\/win32.app.link?%24identity_id=856910924484511566","session_id":"856910924471346045"}
```
=> [SDK-1086] Add Request ID to logs

BranchSDK-Samples/Windows/TestBed/BranchOperations.cpp, BranchSDK/src/BranchIO/Defines.cpp, BranchSDK/src/BranchIO/Defines.h, BranchSDK/src/BranchIO/Event/BaseEvent.cpp, BranchSDK/src/BranchIO/Util/RequestManager.cpp
The Windows Advertising ID requires UWP and is difficult to get to in Win32. But in case an app has it available, the SDK does provide support for it. This change includes it in v1 events if tracking is enabled.
```cpp
branch->getAdvertiserInfo().addId(AdvertiserInfo::WINDOWS_ADVERTISING_ID, "my-waid");
```
```
2020-12-23-16:56:00.466067|Debug|11724|APIClientSession.cpp:117[sendRequest]|Sending request to /v1/open
2020-12-23-16:56:00.466067|Verbose|11724|APIClientSession.cpp:118[sendRequest]|Event Payload: {"app_version":"1.0","branch_key":"key_live_oiT8IkxqCmpGcDT35ttO1fkdExktZD1x","lat_val":0,"os":"Windows 10","os_version":"10.0","sdk":"native","sdk_version":"1.1.2","tracking_disabled":true}
2020-12-23-16:56:00.809279|Debug|11724|APIClientSession.cpp:103[post]|Request sent. Waiting for …
```
=> [SDK-1095] Also send WAID in v1 events if present

BranchSDK-Samples/Windows/TestBed-Local/TestBed-Local.vcxproj, BranchSDK/src/BranchIO/Event/StandardEvent.cpp, BranchSDK/src/BranchIO/Event/StandardEvent.h
Adds support for INITIATE_STREAM and COMPLETE_STREAM v2 events. You can test using TestBed-Local by changing the source code in BranchOperations.cpp from VIEW_ITEM to one of these events.
@BranchMetrics/core-team
=> [CORE-1660] standard events

BranchSDK-Samples/Windows/TestBed-Basic/TestBed-Basic-Package/Product.wxs, BranchSDK-Samples/Windows/TestBed/TextField.cpp
TestBed can crash on occasion because of a signed/unsigned integer comparison when limiting the size of the output text to the text field. This has mainly been observed in TestBed-Basic, but the source code is the same for all flavors.
I'd also like to quickly roll this into master for a better demo/evaluation experience, meaning another PR momentarily.
Also changing the TestBed-Basic MSI to install the Debug build for better logs.
=> [SDK-1117] Fix signed/unsigned comparison issue in TestBed

BranchSDK/src/BranchIO/Branch.cpp, BranchSDK/src/BranchIO/Util/APIClientSession.cpp, BranchSDK/src/BranchIO/Util/APIClientSession.h, BranchSDK/src/BranchIO/Util/RequestManager.cpp
The warning that appears in Visual Studio regarding a Poco::Net::NoCertificateException is entirely benign and expected. See code comments.
This change does not have much impact on behavior. Instead of configuring an ad hoc Context for each request, the SSLManager is used to initialize the default client context, which is then reused with each Context. It's not clear if a Poco HTTPSClientSession can be reused at all on Windows, but SSL Session Caching is always in effect, which minimizes the cost of reconnection.
Some additional logging was also added to better report real failures.
=> [CORE-1740] Improve TLS configuration and handling

BranchSDK-Samples/Windows/TestBed/BranchOperations.cpp, BranchSDK-Samples/Windows/TestBed/TestBed.cpp
There are two changes here.
One is basically a global search and replace in the app to replace `appendText` with `setText`. The output panel will only show the last response. A better option is to improve TestBed along the lines of https://cdn.branch.io/example.html, e.g. separate panels for current request and response. For now, this allows integration tests to pass and is an improvement in terms of readability.
The other change is to call `Branch::openSession` immediately after tracking is reenabled. This is necessary to create a new session without tracking disabled. This is also similar to the Web SDK (https://github.com/BranchMetrics/web-branch-deep-linking-attribution/blob/master/src/6_branch.js#L2376). This change should be included in the SDK in the next release. That will be a …
=> [SDK-1113] updates for testing

BranchSDK/src/BranchIO/LinkInfo.cpp, BranchSDK/test/LinkInfoTest.cpp
This corrects the base64-encoding of control parameters using `Poco::Base64Encoder`. The key is to call `.close()` on the encoder once all data have been appended, as in the example in the gist in a comment.
There was a unit test for long URL creation, but it didn't use control parameters and didn't validate the data parameter. A test has been added for this. This test fails before the second commit and passes afterward.
TestBed-Local now generates valid long links like https://bnc.lt/a/key_live_og1djX2V7XDJ7bWkeGnD5enbxAiq4hcG?feature=testing&data=eyIkY2Fub25pY2FsX3VybCI6Imh0dHBzOlwvXC9qZGVlLmdpdGh1Yi5pb1wvZXhhbXBsZS13aW4zMi5odG1sIiwiJGRlc2t0b3BfdXJsIjoiaHR0cHM6XC9cL2pkZWUuZ2l0aHViLmlvXC9leGFtcGxlLXdpbjMyLmh0bWwiLCIkZGVza3RvcF93ZWJfb3Blbl9kZWxheV9tcyI6IjMwMDAifQ%3D%3D …
=> [INTENG-12752] long url fix

.github/workflows/rmake.yml, conanfile.py
Pinning to a specific version of Poco avoids version drift without lockfiles and stabilizes CI and any other environment using Poco. This can be revisited.
@BranchMetrics/core-team
=> Conanfile updates

.github/workflows/rmake.yml
Auto-generated GHA actions upgrade cpp-branch-deep-linking-attribution. Need to upgrade actions, because of Node v.12 is deprecated (https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) and set-output and save-state commands are deprecated  (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
=> INFRA-XX Auto-update GHA actions

BranchSDK/src/BranchIO/DeviceInfo.cpp, BranchSDK/src/BranchIO/DeviceInfo.h
https://branch.atlassian.net/browse/INTENG-17565
Fix for Desktop App crash/freeze
* Added support for IF_TYPE_IEEE80211 adapters.
* Removed function initMACAddress ( because of legacy function GetAdaptersInfo )
* Code cleanup
Fix Bug for handling unsupported adapters.
- [ ✅] Bug fix (non-breaking change which fixes an issue)
-> Disable ethernet network adapters
-> Run TestBed app
-> It should not freeze/crash
cc @BranchMetrics/saas-sdk-devs for visibility.
=> INTENG-17565 - Fix for app crash/freeze

BranchSDK/src/BranchIO/Event/BaseEvent.cpp, BranchSDK/src/BranchIO/Util/APIClientSession.cpp
https://branch.atlassian.net/browse/INTENG-17552
SetIdentity was not working as expected. In dashboard there was a mismatch between the ids set in SDK and those ones displayed in dashboard. 
Bug Fix.
Steps to reproduce :
1. Login
2. LogEvent 
3. Logout
5. Login again with another id 
6. LogEvent ==> This event still shows previous id.  
For more details please refer to JIRA Ticket
Also removed duplicate logs (These were extra logs added earlier for debugging purpose. They are printed from different places but values are same. They might create confusion to user, so removed them.)
- [X ] Bug fix (non-breaking change which fixes an issue)
Send Commands as mentioned above in steps 1-6. Check if dashboard shows correct dev ids. 
cc @BranchMetrics/saas-sdk-devs for visibility.
=> INTENG 17552 SetIdentity not working issue

.github/workflows/stale.yml
SDK-2190 -- Fix Stale GitHub Action
The current repo-token provided does not have the proper permissions for commenting on and adding labels to issues. To fix this, we can provide the repo's github.token, which would be the default for this action.
Run the GitHub action and observe if the result is successful. 
=> [SDK-2190] Updated token for Stale GHA
